### ISSUE TITLE
Thank you for sharing this online

### ISSUE THREAD

**Issue by dharijanto** [akashmishra242/syncfusion_flutter_calendar#1]
Hi Akash, thanks for sharing this project on GitHub. I came across this while trying to look for Calendar widget that can be used on Flutter! :) 

I tried cloning the code, but I'm only seeing "calender" directory with a few .dart files inside. Do you have a plan to upload the entire source code of the application on the demo video?

Thanks in advance!

**Comment by akashmishra242** [comment]
Hello dharijanto !! thanks for your nice words.  Actually in the repository i have used the 'data of events' from one of my older firebase's project. But do not worry , its very simple to implement 'syncfusion_flutter_calendar' package in your flutter project.

So, what you have do is that in 'sfcalender.dart' file of this repository remove the line of code where i called the data from my firebase (line-18 to line line 32) with your data sourse ( you can create dummy meeting data (.json file ) as well having 'eventName', 'fromDate' , 'toDate', 'BackgrounfColor' intially ) and after that add your meeting data in meeting model as done in line -33. That Set, 
Rest Everything will be same.

Work this out and if still any problem exists feel free to reach me out. I will be more than happy to help you.

Contact me at:
Linkedin: [www.linkedin.com/in/akash-mishra09](http://www.linkedin.com/in/akash-mishra09)
Email: akashmishra242@gmail.com

:) 👍

**Comment by dharijanto** [comment]
Thank you Akash :) have a great day!!
